name: busapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.8
  image_picker: ^0.6.7+4
  image_cropper: 1.0.2
  path: ^1.6.4
  http: ^0.12.1
  firebase_core: 0.4.0+8
  firebase_storage: ^3.1.6
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true
  assets:
    - assets/images/
